platform :ios, '9.0'

target 'MarvelApp' do
  use_frameworks!
  pod 'SDWebImage'

  target 'MarvelAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MarvelAppUITests' do
    # Pods for testing
  end

end
